### ISSUE TITLE
Implement Search Functionality in Contacts List

### ISSUE THREAD

**Issue by soumenkp2** [soumenkp2/Pehchaan#13]
Description:
Enhance the user experience by implementing a search functionality in the Android app. Users should be able to search for their contacts efficiently within the existing contacts list.

Tasks:
    Add a search icon/button in the contacts list interface.
    Implement a search bar that appears upon clicking the search icon/button.
    Enable users to input text into the search bar.
    Implement logic to filter the contacts list based on the user's input.
    Update the contacts list dynamically as the user types in the search bar.
    Provide a clear option to cancel or clear the search and revert to the full contacts list.

Acceptance Criteria:
    Users can initiate a search by clicking on the search icon/button.
    The search bar appears, allowing users to input text.
    The contacts list updates in real-time based on the user's search query.
    Users can easily cancel or clear the search to view the full contacts list.

Additional Considerations:
    Implement smooth and responsive search functionality.
    Ensure a visually pleasing and intuitive design for the search feature.
    Test the search functionality thoroughly on various devices and screen sizes.

Note: This feature aims to improve user convenience by facilitating quick access to specific contacts. The implementation should be user-friendly and align with the overall design principles of the app.

![WhatsApp Image 2024-01-14 at 16 57 56](https://github.com/soumenkp2/Pehchaan/assets/81360450/4f50cea9-26fd-49fa-b825-04e3d62e1d7a)

**Comment by Suryansh1720001** [comment]
@soumenkp2 
I want to work on this issue. Kindly assign it to me

**Comment by soumenkp2** [comment]
Issue is assigned to you now! 
All the best.
