### ISSUE TITLE
Convert Contact List Items to Inflated Card Views

### ISSUE THREAD

**Issue by soumenkp2** [soumenkp2/Pehchaan#15]
Description:
Enhance the Contact List Screen by converting individual contact items into inflated Card Views. This modification will not only improve the visual presentation of contacts but also provide a more structured and appealing user interface.

Tasks:

    Implement Card Views for individual contact items in the Contact List Screen.
    Design the Card Views to display relevant contact information, such as name, profile picture, and other details.
    Ensure that each Card View maintains consistency in terms of size and layout.
    Enhance the visual aesthetics of the Contact List by introducing appropriate styling to the Card Views.
    Test the updated Contact List to confirm that the new Card Views are displayed correctly and interact seamlessly.

Acceptance Criteria:

    Contact List items are transformed into inflated Card Views.
    Each Card View includes essential contact information in a clear and organized manner.
    Card Views exhibit a consistent size and layout for a cohesive appearance.
    The visual styling enhances the overall aesthetics of the Contact List.
    Thoroughly test the Contact List to ensure the proper display and functionality of the new Card Views.

Additional Considerations:

    Optimize the Card Views for responsiveness on various screen sizes.
    Implement subtle animations or transitions to improve the user experience.
    Confirm that the introduction of Card Views does not negatively impact the performance of the Contact List.

Note: The conversion of Contact List items into inflated Card Views aims to elevate the visual appeal and organization of contacts, contributing to an improved user interface.

**Comment by Suryansh1720001** [comment]
@soumenkp2 
I want to work on this issue. Kindly assign it to me

**Comment by soumenkp2** [comment]
Assigned to you, Go ahead. 
Good luck!
