### ISSUE TITLE
[Feature]: add codeql workflow for java

### ISSUE THREAD

**Issue by harmeetsingh11** [soumenkp2/Pehchaan#18]
### Is your feature request related to a problem? Please describe. 

The repository contains code in `java`, it does not have workflow for code scanning. 

### Describe the solution you'd like 

I aim to implement the CodeQL workflow to automate security checks. CodeQL, GitHub's code analysis engine, will identify vulnerabilities in the code and present the findings as code scanning alerts. This workflow will be activated for every push, commit, and pull request through GitHub Actions.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I am willing to work on this issue (optional)
- [X] I am a IWOC'24 contributor

**Comment by soumenkp2** [comment]
Hi @harmeetsingh11 , Thanks for the issue. 
Would you like to work on this?

**Comment by harmeetsingh11** [comment]
Yes @soumenkp2

**Comment by soumenkp2** [comment]
Great @harmeetsingh11 
Issue is assigned to you now. 
Good luck.
