### ISSUE TITLE
Task 2 - Implement Toast Messages on Fragment Entry in Pehchaan App

### ISSUE THREAD

**Issue by soumenkp2** [soumenkp2/Pehchaan#2]
Objective:
Enhance the user experience of the Pehchaan app by adding informative Toast messages whenever the user navigates to a new fragment.

Implementation Steps:

    Identify Fragments:
        Identify the 4 fragments where Toast messages should be displayed upon entry.

    Create Toast Messages:
        Design short and informative Toast messages that convey the purpose or information related to each fragment.

    Implement in XML (if necessary):
        If fragment transitions are controlled via XML layouts, add appropriate attributes to display Toast messages.

    Implement in Java:
        In the Java code associated with fragment transitions, use Toast.makeText to display the corresponding Toast messages.

    Test the Changes:
        Verify that Toast messages are triggered when entering each of the 4 fragments.

Considerations:

    Ensure that the Toast messages are concise and relevant.
    Test the implementation to confirm proper functioning on various devices.

Skills:

    XML
    Java

Expected Project Size:
1-2 hours

Difficulty:
Easy

Additional Notes:
This improvement focuses on providing users with contextual information through Toast messages when navigating to different fragments within the Pehchaan app. The task is straightforward and should be completed efficiently within the estimated time.

**Comment by Suryansh1720001** [comment]
Hey,
I want to work on this issue.
Assign me this @soumenkp2.

**Comment by ShubhAgarwal0704** [comment]
Hey, @soumenkp2 sir plz assign this issue to me

**Comment by soumenkp2** [comment]
Hi @ShubhAgarwal0704 , 
Thank you for taking out this issue. 
Issue is assigned to you now, give it a go. 
All the best.

**Comment by soumenkp2** [comment]
Hello @Suryansh1720001,

I would like Shubh to initially handle this issue. If he encounters any challenges or is unable to resolve it effectively, I'll reassign the task to you. Meanwhile, I plan to add more issues today, so it would be great if you could also review them.
