### ISSUE TITLE
Task 3 - Change Icons

### ISSUE THREAD

**Issue by soumenkp2** [soumenkp2/Pehchaan#3]
Objective:
The task is to enhance the visual appeal of the Pehchaan app by replacing the existing icons in the Bottom Navigation App Bar with new, customized icons.

Implementation Steps:

    Identify Existing Icons:
        Locate the current icons associated with the 4 fragments in the Bottom Navigation App Bar.

    Replace Icons in XML:
        Update the XML layout files associated with the Bottom Navigation App Bar to replace the existing icon references with the newly created icons.

    Implement in Java (if necessary):
        If the icon references are set programmatically in Java, update the code to use the new icons.

    Test the Changes:
        Ensure that the app compiles successfully and that the new icons are displayed correctly in the Bottom Navigation App Bar.

Considerations:

    Maintain consistency with the app's theme and design.
    Verify that the new icons are clear and easily recognizable.
    Keep file sizes in check to avoid impacting app performance.

Skills:

    XML
    Java

Expected Project Size:
1-2 hours

Difficulty:
Easy

Additional Notes:
This improvement focuses on enhancing the visual aesthetics of the Pehchaan app by introducing custom icons. The task is straightforward and should be completed efficiently within the estimated time.

**Comment by praptisharma28** [comment]
Assign me this @soumenkp2 , I can enhance.

**Comment by soumenkp2** [comment]
> Assign me this @soumenkp2 , I can enhance.

Hi there, 
I have assigned you the issue. 
Please go ahead, Thanks :)

**Comment by soumenkp2** [comment]
Hi @praptisharma28 , 
I would like to know an update on the issue to which you have been assigned.

**Comment by praptisharma28** [comment]
Will give the PR today till noon @soumenkp2 .
