### ISSUE TITLE
Redefine the structure of "Add New Contact"

### ISSUE THREAD

**Issue by Suryansh1720001** [soumenkp2/Pehchaan#30]
**Issue Description:**

**Problem 1:**

1. The 'Add Contact' functionality requires the Last Name, but in certain scenarios, it may be more practical to allow the addition of contacts with only the First Name, as the Last Name might not always be available.

**Problem 2:**

2. The Phone Number field currently accepts any number, and there is a need to set a maximum value to ensure valid and manageable phone number inputs when saving a contact.

@soumenkp2 
Assign this issue to me

**Comment by soumenkp2** [comment]
Give it a go! 
Best of luck.
