### ISSUE TITLE
Add the Report Button 

### ISSUE THREAD

**Issue by Suryansh1720001** [soumenkp2/Pehchaan#40]
## Issue Title
Add a "Report" Button for User Feedback

## Issue Description
Currently, there is no direct way for users to report bugs, errors, or issues within the app. To improve user experience and gather valuable feedback, we propose adding a "Report" button. This feature will enable users to easily communicate problems they encounter or provide suggestions for improvement.

## Proposed Solution
Introduce a new button, possibly in the navigation menu, labeled "Report." When users click on this button, it should prompt them to compose an email to the developer with a pre-filled subject line (e.g., "App Feedback") and an email body template that includes information such as app version, device details, and a text field for describing the issue or providing feedback.

## Benefits
1. Facilitates direct communication between users and developers.
2. Streamlines the bug reporting and feedback process.
3. Improves the overall user experience by addressing issues more efficiently.

@soumenkp2  Assign this to me!!

**Comment by soumenkp2** [comment]
Go ahead! 
Best wishes.
