### ISSUE TITLE
[Feature]: Add the github action workflow for greeting contributors 

### ISSUE THREAD

**Issue by praptisharma28** [soumenkp2/Pehchaan#41]
Description:
The current project lacks an automated action to greet contributors. GitHub Actions can significantly enhance project automation. I propose adding a GitHub Action workflow to greet new pull request (PR) and issue creators, fostering a welcoming environment.

Proposed Changes:
Implement a GitHub Action workflow that triggers on new PRs and issues. The workflow should include a greeting message to acknowledge and appreciate the contributors for their efforts.

**Comment by praptisharma28** [comment]
Please assign me this @soumenkp2 under iwoc24

**Comment by soumenpauljar** [comment]
Already present in the project. 
Thanks.

**Comment by soumenkp2** [comment]
Hi @praptisharma28 , 
Automated action to greet contributors is already present in the project. 
Thanks
