### ISSUE TITLE
Task 1 - Send live location with emergency messages (Enhancement)

### ISSUE THREAD

**Issue by soumenkp2** [soumenkp2/Pehchaan#8]
Objective:
Enhance the Android application's emergency section by improving the functionality to send the user's current location via SMS, including a link that opens directly in Google Maps.

Implementation Steps:

    Check Location Permissions:
    Ensure the app checks for location permissions before attempting to retrieve the user's location.

    Retrieve User's Location:
    Use the LocationManager to obtain the user's last known location, prioritizing GPS_PROVIDER for accuracy.

    Generate Google Maps Link:
    Create a Google Maps link using the obtained latitude and longitude: https://www.google.com/maps?q=latitude,longitude.

    Send Location Link via SMS:
    Integrate the Google Maps link into an SMS message and send it programmatically using the SmsManager.

    Inform User:
    Display a user-friendly notification (e.g., Toast) indicating the success or failure of the location sharing process.

Considerations:

    Handle runtime permission requests for accessing the device's location.
    Ensure proper error handling for scenarios where location retrieval is unsuccessful.
    Respect user privacy and comply with relevant laws regarding location sharing.
    Implement this feature ethically, considering the emergency context.

Testing:
Verify the improved functionality on various devices, Android versions, and network conditions. Ensure the Google Maps link opens accurately in the Google Maps app.

Additional Notes:
This enhancement aims to provide a more efficient way for users to share their location during emergencies. It builds upon the existing SMS functionality within the emergency section, offering an improved and user-friendly experience.

**Comment by Suryansh1720001** [comment]
🚀 Excited to work on this! I'll handle the location feature upgrade for the emergency section. Will follow the steps, test thoroughly, and keep the communication channels open for collaboration. Let's make this feature shine!
Kindly assign this issue to me.

**Comment by soumenkp2** [comment]
Hi @Suryansh1720001, 
Thanks for considering this. 
I am happy to assign this issue to you. 
Good luck.
